#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 20 11:24:13 CET 2025
# SW Build 3900603 on Fri Jun 16 19:30:25 MDT 2023
#
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim MatrixMultiplier_TB_behav -key {Behavioral:sim_1:Functional:MatrixMultiplier_TB} -tclbatch MatrixMultiplier_TB.tcl -log simulate.log"
xsim MatrixMultiplier_TB_behav -key {Behavioral:sim_1:Functional:MatrixMultiplier_TB} -tclbatch MatrixMultiplier_TB.tcl -log simulate.log

